### ISSUE TITLE
Radar isn't browsable

### ISSUE THREAD

**Issue by jean** [anoff/devradar#103] opened 2019-11-20 10:51 UTC
I entered 3 technologies in 2 categories. 
The radar shows only 2 blips. When I click on the green one, I see only one item: the list is filtered on the name of one skill. To see others, I have to clear the filter. 

I would expect the radar to show all blips, and to [cluster blips](https://github.com/chancezeus/oms) if they don't fit. (I kind of expected the number displayed on the blip to be a count of the skills. I don't think the skill ID is very useful there.)

Failing that, I would expect the list to be filtered on category and skill level, rather than on the name of the skill that happens to be "on top".

```
[meta]
title = "Rick's skillradar"
categories = [ "Tools", "Techniques", "Platforms", "Frameworks" ]
levels = [ "Novice", "Intermediate", "Advanced", "Veteran" ]

[[blips]]
category = 0
link = ""
description = "Desktop since 1998"
title = "Linux"
level = 3

  [[blips.changes]]
  date = "2019-11"
  newLevel = 3
  text = ""

[[blips]]
category = 3
link = "https://python.org/"
description = "Web, data wrangling, glue code, everything."
title = "Python"
level = 3

  [[blips.changes]]
  date = "2019-11"
  newLevel = 3
  text = ""

[[blips]]
category = 0
link = "https://vim.org"
description = "For everything"
title = "Vim"
level = 3

  [[blips.changes]]
  date = "2019-11"
  newLevel = 3
  text = ""
```

**Comment by anoff** [comment] 2019-11-20 17:35
Hey Jean,
The idea is to actually show each blip on the radar. You should see three and therefore a click on the blip also leads you to exactly that blip and not it's group.

I assume you are running into this issue: https://github.com/anoff/devradar/issues/16

Will verify your radar later. Are you using editor.devradar.io?

**Comment by jean** [comment] 2019-11-21 03:54
Yes, I was using editor.devradar.io

**Comment by anoff** [comment] 2019-11-21 20:44
Yea it seems like 1+3 are overlaying 
![image](https://user-images.githubusercontent.com/7142618/69370882-129f8900-0c9f-11ea-8d2e-1fa8097cf2ee.png)

As expected this is related to #16 which has a problem with short (low entropy) blip titles. 

Assuming I get this bug fixed; would you say that if you have three blips available the fact that a click on each blip links to that specific details is an acceptable behavior?

**Comment by jean** [comment] 2019-11-25 06:10
Yes, a click on a blip leading to that blip's details makes sense to me.

**Comment by anoff** [comment] 2019-11-25 19:01
duplicate of #16

**Closed by anoff** 2019-11-25 19:01 UTC
